// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeResume(arg1:string,arg2:main.AIConfig,arg3:main.JobConfig):Promise<main.AnalysisResult>;

export function ClearResumes():Promise<void>;

export function DeleteResume(arg1:string):Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetResumeText(arg1:string):Promise<string>;

export function GetResumes():Promise<Array<main.Resume>>;

export function ReAnalyzeResume(arg1:string):Promise<void>;

export function RegisterResume(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<boolean|string>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function StartBatchAnalysis(arg1:Array<string>,arg2:main.AIConfig,arg3:main.JobConfig):Promise<void>;

export function TestAIConnection(arg1:main.AIConfig):Promise<boolean|string>;

export function WindowClose():Promise<void>;

export function WindowMaximize():Promise<void>;

export function WindowMinimize():Promise<void>;
