// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeResume(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnalyzeResume'](arg1, arg2, arg3);
}

export function ClearResumes() {
  return window['go']['main']['App']['ClearResumes']();
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteResume(arg1) {
  return window['go']['main']['App']['DeleteResume'](arg1);
}

export function ExportProjectReport(arg1) {
  return window['go']['main']['App']['ExportProjectReport'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjectRanking(arg1) {
  return window['go']['main']['App']['GetProjectRanking'](arg1);
}

export function GetProjectResumes(arg1) {
  return window['go']['main']['App']['GetProjectResumes'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetResumeText(arg1) {
  return window['go']['main']['App']['GetResumeText'](arg1);
}

export function GetResumes() {
  return window['go']['main']['App']['GetResumes']();
}

export function ImportResumesToProject(arg1, arg2) {
  return window['go']['main']['App']['ImportResumesToProject'](arg1, arg2);
}

export function MigrateExistingResumes() {
  return window['go']['main']['App']['MigrateExistingResumes']();
}

export function OpenExportDir() {
  return window['go']['main']['App']['OpenExportDir']();
}

export function ReAnalyzeResume(arg1) {
  return window['go']['main']['App']['ReAnalyzeResume'](arg1);
}

export function RegisterResume(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RegisterResume'](arg1, arg2, arg3, arg4, arg5);
}

export function RegisterResumeToProject(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RegisterResumeToProject'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartBatchAnalysis(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartBatchAnalysis'](arg1, arg2, arg3);
}

export function StartProjectAnalysis(arg1, arg2) {
  return window['go']['main']['App']['StartProjectAnalysis'](arg1, arg2);
}

export function TestAIConnection(arg1) {
  return window['go']['main']['App']['TestAIConnection'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMaximize() {
  return window['go']['main']['App']['WindowMaximize']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}
