// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeResume(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnalyzeResume'](arg1, arg2, arg3);
}

export function ClearResumes() {
  return window['go']['main']['App']['ClearResumes']();
}

export function DeleteResume(arg1) {
  return window['go']['main']['App']['DeleteResume'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetResumeText(arg1) {
  return window['go']['main']['App']['GetResumeText'](arg1);
}

export function GetResumes() {
  return window['go']['main']['App']['GetResumes']();
}

export function ReAnalyzeResume(arg1) {
  return window['go']['main']['App']['ReAnalyzeResume'](arg1);
}

export function RegisterResume(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RegisterResume'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartBatchAnalysis(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartBatchAnalysis'](arg1, arg2, arg3);
}

export function TestAIConnection(arg1) {
  return window['go']['main']['App']['TestAIConnection'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMaximize() {
  return window['go']['main']['App']['WindowMaximize']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}
